# QSN: List the steps to create a 1D array and 2D array

1D array is an array which has 0D elements
1D array can be created by using arange function or simply by passing a list of numbers in the array creation function
for example:

In [1]:
import numpy as np

In [3]:
a=np.array([0,1,2,3,4])
print(a)
print(a.ndim)

[0 1 2 3 4]
1


2D array is an array which has 1D elements
2D array can be created by using array creation function.
for example:

In [9]:
b=np.arange(4)
b

array([0, 1, 2, 3])

In [10]:
b.shape=(2,2)

In [11]:
b

array([[0, 1],
       [2, 3]])

In [12]:
b.ndim

2