1. Get all even numbers from given array.

E.g: arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

output ==> [2, 4, 6, 8, 10, 12, 14] 

Using array concept.

2. Add 5 on every next element of array.

arr = [1, 2, 3, 4, 5, 6, 7]

output = [1, 5, 2, 5, 3, 5, 4, 5, 5, 5, 6, 5, 7, 5]

3. Take 2 1Dim array and try to stack them. Vstack and Hstack. 

4. Take 1Dim array of 9elements, convert into 3x3 2Dim array.

5. 2Dim array find, maximum, minimum, average and sum of 2row 

## QSN 1


In [1]:
import numpy as np

In [2]:
a=np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
print('Following nos are even from the given array:\n')
for i in a:
    if i%2==0:
        print(i,end=' ')
    else:
        continue


Following nos are even from the given array:

2 4 6 8 10 12 14 

## QSN 2

In [21]:
a=np.arange(1,8)
a

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
b=[]
for i in range(len(a)):
    b.append(5)
b

[5, 5, 5, 5, 5, 5, 5]

In [27]:
c=np.dstack((a,b))
c

array([[[1, 5],
        [2, 5],
        [3, 5],
        [4, 5],
        [5, 5],
        [6, 5],
        [7, 5]]])

In [31]:
ANS=np.ravel(c)
ANS

array([1, 5, 2, 5, 3, 5, 4, 5, 5, 5, 6, 5, 7, 5])

## QSN 3

In [32]:
a=np.arange(1,10)
b=np.arange(11,20)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [33]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [34]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

## QSN 4

In [54]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
a.shape=(3,3)

In [56]:
a.ndim

2

## QSN 5

In [57]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
a.shape=(3,3)

In [59]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
a.ndim

2

In [61]:
a.max()

8

In [62]:
a.min()

0

In [63]:
a.mean()

4.0

In [64]:
a[0]+a[1]

array([3, 5, 7])